[[commands]]
package = "golangci-lint"

[[commands]]
package = "treefmt"

[[commands]]
package = "alejandra"

[[commands]]
package = "sqlite-interactive"

[[commands]]
name = "lint"
command = "golangci-lint run && treefmt --fail-on-change"
help = "Run code linters"

[[commands]]
name = "coverage"
command = "go test -v -coverprofile cover.out ./..."
help = "Run code coverage"

[devshell]
name = "spongix"
packages = [
  "diffutils",
  "go_1_18",
  "gotools",
  "gopls",
  "gocode",
  "gcc",
  "fd",
  "gnumake",
  "minio",
  "minio-client"
]
