[[commands]]
package = "golangci-lint"

[[commands]]
name = "lint"
command = "golangci-lint run && treefmt --fail-on-change"
help = "Run code linters"

[[commands]]
name = "coverage"
command = "go test -v -coverprofile cover.out ./..."
help = "Run code coverage"

[devshell]
name = "spongix"
packages = [
  "diffutils",
  "go_1_17",
  "goimports",
  "gopls",
  "gocode",
  "gcc",
  "fd",
  "gnumake",
  "golangci-lint",
  "minio",
  "minio-client",
  "alejandra",
  "diffoscope",
  "treefmt",
]
