imports = [
  "language.go"
]

[[commands]]
package = "go"

[[commands]]
package = "golangci-lint"

[[commands]]
name = "lint"
command = "golangci-lint run && fd -e nix -X nixfmt -c"
help = "Run code linters"

[[commands]]
name = "coverage"
command = "go test -v -coverprofile cover.out ./..."
help = "Run code coverage"

[devshell]
name = "nix-cache-proxy"
packages = [
  "diffutils",
  "go",
  "goimports",
  "gopls",
  "gocode",
  "gcc",
  "fd",
  "nixfmt",
  "gnumake",
  "golangci-lint",
]
